name: tic_tac_toe
channels:
  - defaults
dependencies:
  - pip=24.3.1
  - python=3.11
  - pip:
      - gymnasium==1.0.0
      - numpy==1.26.4
      - typing-extensions==4.12.2
      - matplotlib==3.10.0
      - imageio==2.36.1
      - tensorflow==2.16.1
      - torch==2.2.0
      - jupyter==1.1.1
      - pandas==2.2.3